import { Ticket } from "src/app/modules/uikit/model/tickets.model";

export const ticketsData: Ticket[] =[
  {
    id: 70200,
    titulo: "Cámaras de seguridad",
    empresa: "Grupo Magno",
    descripcion: "Instalación y recableado de 3 cámaras de seguridad IP POE en corporativo grupomagno",
    status: "en proceso",
    fecha_generado: "27/02/2025",
    fecha_asignado: "28/02/2025",
    fecha_atendido: "28/02/2025",
    fecha_resuelto: "28/02/2025",
    username: "Lucas Zamora",
    id_user: 280,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Se envía cotización a cliente para aprobación"
  },
  {
    id: 70201,
    titulo: "Revisión de red",
    empresa: "Grupo Magno",
    descripcion: "Diagnóstico y reparación de fallas en la red LAN de la empresa.",
    status: "pendiente",
    fecha_generado: "01/03/2025",
    fecha_asignado: "02/03/2025",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Ana Pérez",
    id_user: 281,
    prioridad: "Media",
    categoria: "Redes",
    observaciones: "Esperando aprobación del gerente"
  },
  {
    id: 70202,
    titulo: "Mantenimiento de servidores",
    empresa: "Grupo Magno",
    descripcion: "Revisión de temperatura y actualización de firmware en servidores.",
    status: "resuelto",
    fecha_generado: "25/02/2025",
    fecha_asignado: "26/02/2025",
    fecha_atendido: "27/02/2025",
    fecha_resuelto: "28/02/2025",
    username: "Carlos Mendoza",
    id_user: 282,
    prioridad: "Alta",
    categoria: "Mantenimiento",
    observaciones: "Servidores actualizados sin inconvenientes."
  },
  {
    id: 70203,
    titulo: "Instalación de software contable",
    empresa: "Grupo Magno",
    descripcion: "Configuración e instalación de software contable en 5 estaciones de trabajo.",
    status: "en proceso",
    fecha_generado: "02/03/2025",
    fecha_asignado: "03/03/2025",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Mariana Rojas",
    id_user: 283,
    prioridad: "Baja",
    categoria: "Software",
    observaciones: "Instalación parcial, faltan dos equipos."
  },
  {
    id: 70204,
    titulo: "Capacitación en ciberseguridad",
    empresa: "Grupo Magno",
    descripcion: "Capacitación para empleados sobre buenas prácticas en ciberseguridad.",
    status: "pendiente",
    fecha_generado: "05/03/2025",
    fecha_asignado: "06/03/2025",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Pedro García",
    id_user: 284,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Pendiente de confirmación de asistencia."
  }
];
