import { Ticket } from "src/app/modules/uikit/model/tickets.model";

export const ticketsData: Ticket[] =[
  {
    id: 70200,
    titulo: "Cámaras de seguridad",
    empresa: "Grupo Magno",
    descripcion: "Instalación y recableado de 3 cámaras de seguridad IP POE en corporativo grupomagno",
    status: "En proceso",
    fecha_generado: "27/02/2025",
    fecha_asignado: "28/02/2025",
    fecha_atendido: "28/02/2025",
    fecha_resuelto: "28/02/2025",
    username: "Lucas Zamora",
    id_user: 280,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Se envía cotización a cliente para aprobación"
  },
  {
    id: 70201,
    titulo: "Revisión de red",
    empresa: "Grupo Magno",
    descripcion: "Diagnóstico y reparación de fallas en la red LAN de la empresa.",
    status: "Pendiente",
    fecha_generado: "01/03/2025",
    fecha_asignado: "02/03/2025",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Ana Pérez",
    id_user: 281,
    prioridad: "Media",
    categoria: "Redes",
    observaciones: "Esperando aprobación del gerente"
  },
  {
    id: 70202,
    titulo: "Mantenimiento de servidores",
    empresa: "Grupo Magno",
    descripcion: "Revisión de temperatura y actualización de firmware en servidores.",
    status: "Perdido",
    fecha_generado: "25/02/2025",
    fecha_asignado: "26/02/2025",
    fecha_atendido: "27/02/2025",
    fecha_resuelto: "28/02/2025",
    username: "Carlos Mendoza",
    id_user: 282,
    prioridad: "Alta",
    categoria: "Mantenimiento",
    observaciones: "Servidores actualizados sin inconvenientes."
  },
  {
    id: 70203,
    titulo: "Instalación de software contable",
    empresa: "Grupo Magno",
    descripcion: "Configuración e instalación de software contable en 5 estaciones de trabajo.",
    status: "En proceso",
    fecha_generado: "02/03/2025",
    fecha_asignado: "03/03/2025",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Mariana Rojas",
    id_user: 283,
    prioridad: "Baja",
    categoria: "Software",
    observaciones: "Instalación parcial, faltan dos equipos."
  },
  {
    id: 70204,
    titulo: "Capacitación en ciberseguridad",
    empresa: "Grupo Magno",
    descripcion: "Capacitación para empleados sobre buenas prácticas en ciberseguridad.",
    status: "Pendiente",
    fecha_generado: "05/03/2025",
    fecha_asignado: "06/03/2025",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Pedro García",
    id_user: 284,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Pendiente de confirmación de asistencia."
  },
  {
    id: 70210,
    titulo: "Actualización de firewall",
    empresa: "Grupo Magno",
    descripcion: "Configuración y actualización del firewall perimetral para mejorar la seguridad de la red.",
    status: "Pendiente",
    fecha_generado: "08/03/2025",
    fecha_asignado: "",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Javier Morales",
    id_user: 285,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Esperando autorización del departamento de TI."
  },
  {
    id: 70211,
    titulo: "Instalación de VPN",
    empresa: "Grupo Magno",
    descripcion: "Implementación de una VPN para acceso remoto seguro a la red corporativa.",
    status: "Pendiente",
    fecha_generado: "09/03/2025",
    fecha_asignado: "",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Luis Fernández",
    id_user: 286,
    prioridad: "Alta",
    categoria: "Redes",
    observaciones: "Pendiente de revisión de configuración de acceso."
  },
  {
    id: 70212,
    titulo: "Revisión de vulnerabilidades en servidores",
    empresa: "Grupo Magno",
    descripcion: "Análisis de seguridad para identificar vulnerabilidades en los servidores de producción.",
    status: "Pendiente",
    fecha_generado: "10/03/2025",
    fecha_asignado: "",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Sofía Ramírez",
    id_user: 287,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Esperando informe de auditoría externa."
  },
  {
    id: 70213,
    titulo: "Configuración de backups automatizados",
    empresa: "Grupo Magno",
    descripcion: "Implementación de backups automáticos en servidores críticos.",
    status: "Pendiente",
    fecha_generado: "11/03/2025",
    fecha_asignado: "",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Fernando López",
    id_user: 288,
    prioridad: "Alta",
    categoria: "Mantenimiento",
    observaciones: "Pendiente de configuración en almacenamiento en la nube."
  },
  {
    id: 70214,
    titulo: "Investigación de acceso no autorizado",
    empresa: "Grupo Magno",
    descripcion: "Análisis de registros y auditoría de accesos sospechosos en la red corporativa.",
    status: "Pendiente",
    fecha_generado: "12/03/2025",
    fecha_asignado: "",
    fecha_atendido: "",
    fecha_resuelto: "",
    username: "Andrea Castillo",
    id_user: 289,
    prioridad: "Alta",
    categoria: "Seguridad y vigilancia",
    observaciones: "Esperando resultados del monitoreo de red."
  }

];
