import { User } from 'src/app/modules/uikit/model/user.model';

export const dummyData: User[] = [
  {
    id: 1,
    name: 'Dimas López',
    age: 21,
    username: 'dimaslopez',
    email: 'dimas@gruposaom.com.mx',
    phone: '9981862431',
    department: 'Development',
    occupation: 'Software Engineer',
    selected: false,
    status: 1,
    created_at: '2024-10-12T12:34:56Z',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 25,
    username: 'janesmith',
    email: 'jane.smith@example.com',
    phone: '+1-202-555-0123',
    department: 'Design',
    occupation: 'Graphic Designer',
    selected: false,
    status: 1,
    created_at: '2024-10-14T12:34:56Z',
  },
  {
    id: 3,
    name: 'Michael Brown',
    age: 35,
    username: 'michaelb',
    email: 'michael.brown@example.com',
    phone: '+1-202-555-0189',
    department: 'Data',
    occupation: 'Data Scientist',
    selected: true,
    status: 2,
    created_at: '2024-10-16T12:34:56Z',
  },
  {
    id: 4,
    name: 'Emily White',
    age: 28,
    username: 'emilyw',
    email: 'emily.white@example.com',
    phone: '+1-202-555-0147',
    department: 'Marketing',
    occupation: 'Marketing Specialist',
    selected: false,
    status: 2,
    created_at: '2024-10-18T12:34:56Z',
  },
  {
    id: 5,
    name: 'David Johnson',
    age: 40,
    username: 'davidj',
    email: 'david.johnson@example.com',
    phone: '+1-202-555-0168',
    department: 'Ventas',
    occupation: 'Product Manager',
    selected: true,
    status: 1,
    created_at: '2024-10-20T12:34:56Z',
  },
  {
    id: 6,
    name: 'Sarah Davis',
    age: 32,
    username: 'sarahd',
    email: 'sarah.davis@example.com',
    phone: '+1-202-555-0190',
    department: 'Ventas',
    occupation: 'UI/UX Designer',
    selected: false,
    status: 1,
    created_at: '2024-10-22T12:34:56Z',
  },
  {
    id: 7,
    name: 'Chris Lee',
    age: 29,
    username: 'chrislee',
    email: 'chris.lee@example.com',
    phone: '+1-202-555-0134',
    department: 'Ventas',
    occupation: 'Mobile Developer',
    selected: false,
    status: 1,
    created_at: '2024-10-26T12:34:56Z',
  },
  {
    id: 8,
    name: 'Emma Wilson',
    age: 27,
    username: 'emmawilson',
    email: 'emma.wilson@example.com',
    phone: '+1-202-555-0175',
    department: 'Ventas',
    occupation: 'DevOps Engineer',
    selected: true,
    status: 3,
    created_at: '2024-10-28T12:34:56Z',
  },
];
